### PR TITLE
Update php.yml

### PR DESCRIPTION
**Pull request by FredoVelcro**
Fix bad escaping in namespaces

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi,
can you please update also in ``certificationy/symfony-pack`` ? 

Thank you

**Comment by mickaelandrieu** [comment]
ping @FredoVelcro ?

**Comment by FredoVelcro** [comment]
Hi,

Already done !

**Comment by mickaelandrieu** [comment]
sorry, need to sleep more :cat: 

Thank you

**Comment by FredoVelcro** [comment]
héhé ! no pb ;)

**Pull request merged**
