### PR TITLE
[Feature] Add help answers

### PR DESCRIPTION
**Pull request by 20uf**
Hello,

This PR is related to PR: https://github.com/certificationy/certificationy-cli/pull/33

Regards,

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Tests dont pass, also you should add new ones for the features you want to introduce.

Then, I agree for an help message but not for a versions property: for Symfony I'll create a Symfony 3 pack from Symfony 2 pack.

**Comment by 20uf** [comment]
@thanks @mickaelandrieu.

All right!
But I do not think your solution is the right one, we will certainly find questions of the pack SF2 and SF3.

**Comment by mickaelandrieu** [comment]
@20uf I need to think a little bit about it.

Lets get tests green for the help message feature.

I will probably push a 2.x branch soon as I'm working on new API for this library

**Comment by 20uf** [comment]
@mickaelandrieu The unit tests do not pass on the master branch. 
The problem is not related to my PR.

You can look ?

**Comment by mickaelandrieu** [comment]
@20uf yes, I've fixed the pack and re-started the build ;)

**Comment by 20uf** [comment]
@mickaelandrieu I removed the versions, so this feature only concerns questions help.

**Comment by mickaelandrieu** [comment]
@20uf  LGTM, also I still don't know how to deal with each version of a pack right now :/

Thanks for your PR :)

**Comment by 20uf** [comment]
@mickaelandrieu thanks for the merge.

I think above all about reduce complexity, creating several packs would  have already a risk of similar questions, or missing if pack 2 and 3 are not loaded together.

In addition the filtering is possible with my method, maybe after is not a useful information visually, in my opinion it is.

Can you look at the PRhttps://github.com/certificationy/certificationy-cli/pull/33 ?

**Pull request merged**
